### ISSUE TITLE
Refine log in / logged out experience

### ISSUE THREAD

**Issue by jimenezmiguela** [jimenezmiguela/Help_Find#19]
Seeking ideas to improve user experience, i.e.: 1. Hide password. 2. Eliminate redundancy. 3. Create a more useful purpose for needing a login/out.

**Comment by olegkolyaka78** [comment]
Good ideas. Lets split them into separate tickets, for example:

1. In user sign up block show asterisks or dots in password field instead of symbols being entered by user. For example, 
![image](https://user-images.githubusercontent.com/63619892/161386299-daf282e4-727b-440b-a84b-0245c62194f2.png)
 
2. In user log in block show asterisks or dots in password field instead of symbols being entered by user. For example, 
![image](https://user-images.githubusercontent.com/63619892/161386299-daf282e4-727b-440b-a84b-0245c62194f2.png)

3. In user sign up block create button to show symbols used as a password in password field For example, 
![image](https://user-images.githubusercontent.com/63619892/161386448-0cd7828c-5226-4f32-b7ab-d183ec8eaee1.png)
When user clicks on button password becomes visible and button changes from open eye to crossed eye. For example, 
![image](https://user-images.githubusercontent.com/63619892/161386547-ec7b0ab7-cd92-44c8-ab81-893bdc07cae7.png)

4. In user log in block create button to show symbols used as a password in password field For example, 
![image](https://user-images.githubusercontent.com/63619892/161386448-0cd7828c-5226-4f32-b7ab-d183ec8eaee1.png)
When user clicks on button password becomes visible and button changes from open eye to crossed eye. For example, 
![image](https://user-images.githubusercontent.com/63619892/161386547-ec7b0ab7-cd92-44c8-ab81-893bdc07cae7.png)

Any other ideas are welcome.

**Comment by jimenezmiguela** [comment]
Sounds great!  Separating tickets...
